In [1]:
from pathlib import Path
import glob
import os
import numpy as np
import pandas as pd
from tqdm import tqdm

import open3d as o3d
import nibabel as nib
from skimage.measure import marching_cubes


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [7]:
DATA_ROOT = Path("D:/ADLM_Data/samples")
TARGET_ROOT = "D:/ADLM_Data/decimated"
VERTICES = 25000
EXTENSION = ".ply"
LIMIT = 2
COUNT = 0

In [8]:
for file in tqdm(os.listdir(str(DATA_ROOT))):
    _path = str(os.path.join(str(DATA_ROOT), file).replace('\\', '/')) +'/body_mask.nii.gz'
    
    _id = _path[_path[:_path.rfind("/")].rfind("/")+1:_path.rfind("/",0,)]
    
    if (LIMIT > COUNT) :
        if(os.path.exists(_path)):
        
            body_segment = nib.load(_path)
            body_segment_data = body_segment.get_fdata()

            verts, faces, _, __ = marching_cubes(body_segment_data, level=0, step_size=1)
            verts = verts/np.array(body_segment_data.shape) 

            mesh = o3d.geometry.TriangleMesh(vertices=o3d.utility.Vector3dVector(np.asarray(verts)),
                                        triangles=o3d.utility.Vector3iVector(np.asarray(faces)))

            decimated_mesh = o3d.geometry.TriangleMesh.simplify_quadric_decimation(mesh, VERTICES)

            _target_path =  TARGET_ROOT + "/" + _id + EXTENSION
            o3d.io.write_triangle_mesh( _target_path, decimated_mesh)
            print('\r' + str(COUNT) + "written", end='')
            COUNT += 1
        else:
            continue
    else:
        break

 25%|█████████████████████                                                               | 1/4 [00:07<00:22,  7.46s/it]

0written

 50%|██████████████████████████████████████████                                          | 2/4 [00:14<00:14,  7.07s/it]

1written

In [33]:
ex_path = "/vol/chameleon/projects/mesh_gnn/body_meshes_decimated/4105794.off"

In [34]:
decimated = o3d.io.read_triangle_mesh(ex_path)

In [35]:
decimated

TriangleMesh with 13458 points and 24999 triangles.

In [2]:
ex_path= "C:/Users/aorhu/Masaüstü/body_mask.nii.gz"

In [3]:
body_segment = nib.load(ex_path)
body_segment_data = body_segment.get_fdata()

In [4]:
verts, faces, norms, vals = marching_cubes(body_segment_data, level=0, step_size=1)

In [5]:
verts = verts/np.array(body_segment_data.shape) 

In [8]:
mesh = o3d.geometry.TriangleMesh(vertices=o3d.utility.Vector3dVector(np.asarray(verts)),
                                 triangles=o3d.utility.Vector3iVector(np.asarray(faces)))
mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh],mesh_show_back_face=True,mesh_show_wireframe=True)

In [12]:
decimated_mesh = o3d.geometry.TriangleMesh.simplify_quadric_decimation(mesh, 5000)

In [13]:
decimated_mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([decimated_mesh],mesh_show_back_face=True,mesh_show_wireframe=True)

In [14]:
o3d.io.write_triangle_mesh("4266049_5.ply", decimated_mesh, print_progress=True )

True

In [ ]:
----------------------------------------------------

In [ ]:
1000071 = 545964  >>  25000, 
1000125 = 506972  >>  25000,
1002371 = 515692  >>  25000,
1787929 = 618378  >>  24999,

In [58]:
_path = Path("C:/Users/aorhu/Masaüstü/Yeni klasör/1002371/body_mask.nii.gz")

In [59]:
body_segment = nib.load(_path)
body_segment_data = body_segment.get_fdata()
verts, faces, _, __ = marching_cubes(body_segment_data, level=0, step_size=1)
verts = verts/np.array(body_segment_data.shape) 

mesh = o3d.geometry.TriangleMesh(vertices=o3d.utility.Vector3dVector(np.asarray(verts)),
                             triangles=o3d.utility.Vector3iVector(np.asarray(faces)))

decimated_mesh = o3d.geometry.TriangleMesh.simplify_quadric_decimation(mesh, 25000)

In [37]:
mesh.triangles

std::vector<Eigen::Vector3i> with 506972 elements.
Use numpy.asarray() to access data.

In [56]:
np.asarray(mesh.vertices)[:10]

array([[0.01339286, 0.36309524, 0.85430464],
       [0.01785714, 0.36309524, 0.85099338],
       [0.01785714, 0.35714286, 0.85430464],
       [0.01785714, 0.36309524, 0.85761589],
       [0.01339286, 0.36904762, 0.85430464],
       [0.01785714, 0.36904762, 0.85099338],
       [0.01785714, 0.36904762, 0.85761589],
       [0.01339286, 0.375     , 0.85430464],
       [0.01785714, 0.375     , 0.85099338],
       [0.01785714, 0.36904762, 0.85761589]])

In [44]:
np.asarray(mesh.triangles)

array([[     2,      1,      0],
       [     0,      3,      2],
       [     0,      1,      4],
       ...,
       [253463, 253480, 253479],
       [253480, 253472, 253467],
       [253472, 253480, 253469]], dtype=int32)

In [53]:
count = 0
lst = []
for elem in np.asarray(mesh.triangles):
    if 0 in elem:
        lst.append(elem)
        count+=1

In [54]:
lst

[array([2, 1, 0], dtype=int32),
 array([0, 3, 2], dtype=int32),
 array([0, 1, 4], dtype=int32),
 array([3, 0, 6], dtype=int32),
 array([6, 0, 4], dtype=int32)]

In [55]:
count

5

In [43]:
np.asarray(mesh.triangles)[2]

array([0, 1, 4], dtype=int32)

In [38]:
mesh.vertices

std::vector<Eigen::Vector3d> with 253481 elements.
Use numpy.asarray() to access data.

In [39]:
decimated_mesh.triangles

std::vector<Eigen::Vector3i> with 25000 elements.
Use numpy.asarray() to access data.

In [61]:
decimated_mesh.vertices

std::vector<Eigen::Vector3d> with 13279 elements.
Use numpy.asarray() to access data.

In [60]:
decimated_mesh_paint = np.asarray([230,200,110])/255.0
decimated_mesh.paint_uniform_color(decimated_mesh_paint)
decimated_mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([decimated_mesh],mesh_show_back_face=True,mesh_show_wireframe=True)